version: "3.9"

services:
  nginx-reverse:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - internal
    depends_on:
      - idk-backend

  idk-backend:
    build:
      context: ../idk-backend
      dockerfile: ./Dockerfile
    environment:
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_URL
    depends_on:
      - db
    networks:
      - backend
    expose:
      - 8080
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: master
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    expose:
      - 5432
    restart: always

networks:
  internal:
    driver: bridge
    external: false

volumes:
  db-data:
